
### ========================= USER API: 8082
### GET USER BY ID
GET http://localhost:8082/users/2;

### GET ALL USERS
GET http://localhost:8082/users/all;

### REGISTER USER
GET http://localhost:8082/users/create;

### SUBSCRIBE TO A USER
GET http://localhost:8082/users/3/subscribe/2


# ========================= ARTICLE API: 8081
### CREATE ARTICLE
GET http://localhost:8083/articles/create/2

### ALL ARTICLES
GET http://localhost:8083/articles/all

###
GET http://localhost:8081/

### GET ARTICLE BY ID
GET http://localhost:8081/articles/2

### ========================= NOTIFICATION API: 3000
GET http://localhost:3000/notifications/users/3/subscribe/2

### TEST
GET http://localhost:3000/

### NEW ARTICLE NOTIFICATION
GET http://localhost:3000/notifications/newArticle/1/user/2


### MONOLIT API
GET http://localhost:8080/blog/articles

###
GET http://localhost:8080/blog/articles/new/1

###
GET http://localhost:8080/blog/users

###
GET http://localhost:8080/blog/1/subscribe/2

###
GET http://localhost:8080/blog/1/unSubscribe/2

### ========================= DOCKER
GET http://localhost:8082/users/all