
### ========================= USER API
#GET USER BY ID
GET http://localhost:8082/users/2;

# GET ALL USERS
###
GET http://localhost:8082/users/all;

# REGISTER USER
###
GET http://localhost:8082/users/create;

###
GET http://localhost:8082/users/1/subscribe/2

# ========================= ARTICLE API
### CREATE ARTICLE
GET http://localhost:8081/articles/create/2

### ALL ARTICLES
GET http://localhost:8083/articles/all