---
version: '3'
services:
  articleservice:
    build: ./article-service
    container_name: article_service
    ports:
      - "8083:8080"
    networks:
      - my_network
  userservice:
    build: ./user-service
    container_name: userservice
    ports:
      - "8082:8080"
    networks:
      - my_network
  notifications:
    container_name: notifications
    build: ./notifications
    ports:
      - "3000:3000"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge